// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/mine/sidebar";
import { MdOutlineSupervisorAccount } from "react-icons/md";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const brands=["perfora","mama_earth","boat"]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-100%">
        <div className="flex justify-between h-screen sticky top-0 px-2 flex-col py-6">
          <div className="flex flex-col items-center gap-2">
            {brands.map((brand,index)=>{
                return <img key={brand} src={`/icons/company/${brand}.svg`} alt={brand} className={`w-10 h-10 ${index==0?"mb-4":""}`} />
            })}
          </div>
          <div className="flex flex-col gap-4 items-center">
            <MdOutlineSupervisorAccount size={24}/>
            <Avatar>
              <AvatarImage src="https://avatars.githubusercontent.com/u/188852207?s=40&v=4" />
              <AvatarFallback>SS</AvatarFallback>
            </Avatar>
          </div>

        </div>
          <Sidebar/>
          {children}
        </div>
      </body>
    </html>
  );
}
